<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="DocFx.App" Version="2.78.5" />
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="2.0.2" />
    <PackageVersion Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageVersion Include="Microsoft.Bcl.Memory" Version="10.0.5" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis" Version="5.3.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.3.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.5.2" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="Scriban" Version="7.0.6" />
    <PackageVersion Include="System.Linq.Async" Version="[6.0.3]" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <GlobalPackageReference Include="Meziantou.Analyzer" Version="3.0.28" PrivateAssets="All" />
    <GlobalPackageReference Include="Meziantou.Polyfill" Version="1.0.105" PrivateAssets="All" />
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.201" PrivateAssets="All" />
  </ItemGroup>
</Project>
